#ifndef OPEN_GL_ENUMS_H
#define OPEN_GL_ENUMS_H


namespace jomike{


enum class Texture_Target{TEXTURE_1D, TEXTURE_2D, TEXTURE_3D, TEXTURE_CUBE_MAP};

enum class GL_Statuses{
	DELETE_STATUS = 0
	, LINK_STATUS
	, VALIDATE_STATUS
	, INFO_LOG_LENGTH
	, ATTACHED_SHADERS
	, ACTIVE_ATOMIC_COUNTER_BUFFERS
	, ACTIVE_ATTRIBUTES
	, ACTIVE_ATTRIBUTE_MAX_LENGTH
	, ACTIVE_UNIFORMS
	, ACTIVE_UNIFORM_MAX_LENGTH
	, PROGRAM_BINARY_LENGTH
	, COMPUTE_WORK_GROUP_SIZE
	, TRANSFORM_FEEDBACK_BUFFER_MODE
	, TRANSFORM_FEEDBACK_VARYINGS
	, TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH
	, GEOMETRY_VERTICES_OUT
	, GEOMETRY_INPUT_TYPE
	, GEOMETRY_OUTPUT_TYPE
};

enum class Array_Draw_Mode{
	POINTS = 0
	, LINE_STRIP
	, LINE_LOOP
	, LINES
	, LINE_STRIP_ADJACENCY
	, LINES_ADJACENCY
	, TRIANGLE_STRIP
	, TRIANGLE_FAN
	, TRIANGLES
	, TRIANGLE_STRIP_ADJACENCY
	, TRIANGLES_ADJACENCY
	, PATCHES
};


enum class GL_Buffer_Targets{
	ARRAY_BUFFER = 0
	, ATOMIC_COUNTER_BUFFER
	, COPY_READ_BUFFER
	, COPY_WRITE_BUFFER
	, DRAW_INDIRECT_BUFFER
	, DISPATCH_INDIRECT_BUFFER
	, ELEMENT_ARRAY_BUFFER
	, PIXEL_PACK_BUFFER
	, PIXEL_UNPACK_BUFFER
	, QUERY_BUFFER
	, SHADER_STORAGE_BUFFER
	, TEXTURE_BUFFER
	, TRANSFORM_FEEDBACK_BUFFER
	, UNIFORM_BUFFER
};

enum class GL_Sized_Internal_Formats{
	R8 = 0
	, R8_SNORM
	, R16
	, R16_SNORM
	, RG8
	, RG8_SNORM
	, RG16
	, RG16_SNORM
	, R3_G3_B2
	, RGB4
	, RGB5
	, RGB8
	, RGB8_SNORM
	, RGB10
	, RGB12
	, RGB16_SNORM
	, RGBA2
	, RGBA4
	, RGB5_A1
	, RGBA8
	, RGBA8_SNORM
	, RGB10_A2
	, RGB10_A2UI
	, RGBA12
	, RGBA16
	, SRGB8
	, SRGB8_ALPHA8
	, R16F
	, RG16F
	, RGB16F
	, RGBA16F
	, R32F
	, RG32F
	, RGB32F
	, RGBA32F
	, R11F_G11F_B10F
	, RGB9_E5
	, R8I
	, R8UI
	, R16I
	, R16UI
	, R32I
	, R32UI
	, RG8I
	, RG8UI
	, RG16I
	, RG16UI
	, RG32I
	, RG32UI
	, RGB8I
	, RGB8UI
	, RGB16I
	, RGB16UI
	, RGB32I
	, RGB32UI
	, RGBA8I
	, RGBA8UI
	, RGBA16I
	, RGBA16UI
	, RGBA32I
	, RGBA32UI
};

enum class GL_Pixel_Formats{
	RED
	, RG
	, RGB
	, BGR
	, RGBA
	, BGRA
	, DEPTH_COMPONENT
	, STENCIL_INDEX
};

enum class GL_Attachment_Points{
	COLOR_ATTACHMENT0
	, COLOR_ATTACHMENT1
	, COLOR_ATTACHMENT2
	, COLOR_ATTACHMENT3
	, COLOR_ATTACHMENT4
	, COLOR_ATTACHMENT5
	, COLOR_ATTACHMENT6
	, COLOR_ATTACHMENT7
	, COLOR_ATTACHMENT8
	, COLOR_ATTACHMENT9
	, COLOR_ATTACHMENT10
	, COLOR_ATTACHMENT11
	, COLOR_ATTACHMENT12
	, COLOR_ATTACHMENT13
	, COLOR_ATTACHMENT14
	, COLOR_ATTACHMENT15
	, DEPTH_ATTACHMENT
	, STENCIL_ATTACHMENT
	, DEPTH_STENCIL_ATTACHMENT
};

enum class GL_Draw_Types{
	STATIC
	, DYNAMIC
};

enum class GL_Types{

	BYTE
	, UNSIGNED_BYTE
	, SHORT
	, UNSIGNED_SHORT
	, INT
	, UNSIGNED_INT
	, HALF_FLOAT
	, FLOAT
	, DOUBLE
	, FIXED
	, INT_2_10_10_10_REV
	, UNSIGNED_INT_2_10_10_10_REV
	, UNSIGNED_INT_10F_11F_11F_REV

};

enum class Texture_Wrap_Type{
	CLAMP_TO_EDGE
	, CLAMP_TO_BORDER
	, MIRRORED_REPEAT
	, REPEAT
	, MIRROR_CLAMP_TO_EDGE
};

}

#endif //OPEN_GL_ENUMS_H


